name: Docker Image CI

on:
  push:
    branches: [ "CI_test" ]
  pull_request:
    branches: [ "CI_test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: x=$(date +%s) && docker build . --file Dockerfile --tag gray-scott-sim-2023-group8:$x

    - name: print
      run: print($x)

    - name: test
      run: docker run gray-scott-sim-2023-group8:$x ./gstesting
