name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set current date as env variable
      run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gray-scott-sim-2023-group8:$NOW

    - name : test
      run : docker run gray-scott-sim-2023-group8:$NOW ./gstesting
