name: Docker Image CI

on:
  push:
    branches: [ "CI_test" ]
  pull_request:
    branches: [ "CI_test" ]

env:
  var: date +%s

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: print
      run: echo $var
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gray-scott-sim-2023-group8:$var

    - name : test
      run : docker run gray-scott-sim-2023-group8:$var ./gstesting
